name: 'OpenJDK Mobile Static Release'

on:
  push:
    tags:
      - '*'

jobs:
  build-android-linux-aarch64:
    name: android-linux-aarch64
    uses: ./.github/workflows/build-android-static.yml
    with:
      platform: linux-x64
      gcc-major-version: '10'

  build-ios-macos-aarch64:
    name: ios-macos-aarch64
    uses: ./.github/workflows/build-ios-static.yml
    with:
      platform: macos-aarch64
      runs-on: 'macos-14'
      xcode-toolset-version: '14.3.1'

  early-access:
    needs: [ build-android-linux-aarch64, build-ios-macos-aarch64 ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-linux-aarch64
          path: ./dist/
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-macos-aarch64
          path: ./dist/
      - name: Check downloads
        run: |
          pwd
          ls -R ./dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/android-linux-aarch64
            ./dist/ios-macos-aarch64
